
version: "3.1"

services:
    web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - .:/var/www/html
          - ./compose/nginx/site.conf:/etc/nginx/conf.d/default.conf
      networks:
          - app-network
    php:
      build:
        context: .
        dockerfile: ./compose/php-fpm/Dockerfile
      working_dir: /var/www/html/public
      volumes:
          - .:/var/www/html
      networks:
          - app-network


networks:
    app-network:
        driver: bridge